# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "almalinux/9"

  config.vm.provision "ansible" do |ansible|
    #ansible.verbose = "vvv"
    ansible.playbook = "provisioning/playbook.yml"
    ansible.become = "true"
  end

  config.vm.provider "virtualbox" do |v|
	  v.memory = 2048
  end

  config.vm.define "ns01" do |ns01|
    ns01.vm.network "public_network", ip: "172.22.23.106", netmask: "255.255.252.0"
    ns01.vm.hostname = "ns01"
  end

  config.vm.define "client" do |client|
    client.vm.network "public_network", ip: "172.22.23.107", netmask: "255.255.252.0"
    client.vm.hostname = "client"
  end

end
