networks:
  web:
    external: true
  db:
    external: true
      
services:

  redmine:
    build: ./build
    restart: always
    networks:
      - web
      - db
    ports:
      - 8080:3000
    environment:
      REDMINE_DB_MYSQL: db
      REDMINE_DB_PASSWORD: example
      REDMINE_SECRET_KEY_BASE: supersecretkey

  db:
    image: mysql:8.0
    restart: always
    networks:
      - db
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: redmine
    volumes:
      - ./data:/var/lib/mysql