# -*- mode: ruby -*-
# vi: set ft=ruby :
$hosts = 3
$disk = 3
Vagrant.configure("2") do |config|
  config.vm.provider "virtualbox" do |vm|
    vm.memory = 2048
    vm.cpus = 2
    vm.check_guest_additions=false
  config.vm.box = "ubuntu/jammy64"
  config.vm.box_check_update = false
  config.vm.synced_folder "C:\\Users\\levitskyav\\Documents\\share_vm", "/home/vagrant/data" # Введите путь к директории на вашей локальной машине.
                                                                                             # для подключения шары, после vagrant up нужно выполнить
                                                                                             # vagrant reload, так как подклюится только после установки
                                                                                             # VBoxGuestAdditions
end

(0..$hosts-1).each do |i|
    config.vm.define "otus-node-#{i}" do |node|
        node.vm.network "public_network", ip: "172.22.23.#{105+i}", netmask: "255.255.252.0"
        node.vm.hostname = "otus-node-#{i}.local"
        node.vm.disk :disk, size: "50GB", primary: true
        (1..$disk).each do |d|
          node.vm.disk :disk, size: "20GB", name: "disk-#{d}"
        end
    end

end
  config.vm.provision "shell", inline: <<-SHELL
    apt update -y && apt upgrade -y
    apt install ncdu htop tree mc vim traceroute net-tools tcpdump curl wget git -y
    cp -r /vagrant/authorized_keys /root/.ssh/authorized_keys
    cp -r /vagrant/.bashrc /home/vagrant && cp -r /vagrant/.bashrc /root/
    cd /vagrant/VBoxGuestAdditions && sh ./VBoxLinuxAdditions.run
    timedatectl set-timezone Europe/Moscow
    reboot
  SHELL
end
