# -*- mode: ruby -*-
# vi: set ft=ruby :
$hosts = 4
$disk = 3
Vagrant.configure("2") do |config|
  config.vm.provider "virtualbox" do |vm|
    vm.memory = 2048
    vm.cpus = 2
    vm.check_guest_additions=false
  config.vm.box = "ubuntu/jammy64"
  config.vm.box_check_update = false
end

(1..$hosts).each do |i|
    config.vm.define "otus-node-#{i}" do |node|
        node.vm.network "public_network", ip: "172.22.23.#{105+i}", netmask: "255.255.252.0"
        node.vm.hostname = "otus-node-#{i}"
        node.vm.disk :disk, size: "50GB", primary: true
        (1..$disk).each do |d|
          node.vm.disk :disk, size: "20GB", name: "disk-#{d}" 
#        config.vm.provision "shell",
#          inline: "cp -r /vagrant/node#{i}_50-vagrant.yaml /etc/netplan/50-vagrant.yaml"
        end
    end

end
  config.vm.provision "shell", inline: <<-SHELL
#    apt update -y
#    apt upgrade -y
    cp -r /vagrant/authorized_keys /root/.ssh/authorized_keys
#    netplan apply
    timedatectl set-timezone Europe/Moscow
  SHELL
end