# -*- mode: ruby -*-
# vi: set ft=ruby :
$hosts = 3                              # укажите колличество вм
$disk = 4                               # укажите колличество дисков
Vagrant.configure("2") do |config|
  config.vm.provider "virtualbox" do |vm|
    vm.memory = 2048
    vm.cpus = 2
    vm.check_guest_additions=false
  config.vm.box = "ubuntu/jammy64"
  config.vm.box_check_update = false
end

(0..$hosts-1).each do |i|
    config.vm.define "otus-node-#{i}" do |node|
        node.vm.network "public_network", ip: "172.22.23.#{105+i}", netmask: "255.255.252.0"
        node.vm.hostname = "otus-node-#{i}.local"
        node.vm.disk :disk, size: "50GB", primary: true
        (1..$disk).each do |d|
          node.vm.disk :disk, size: "20GB", name: "disk-#{d}"
        end
    end

end
  config.vm.provision "shell", inline: <<-SHELL
    apt update -y && apt upgrade -y
    cp -r /vagrant/authorized_keys /root/.ssh/authorized_keys             # Добавьте вашу публичную часть ключа
    cp -r /vagrant/.bashrc /home/vagrant && cp -r /vagrant/.bashrc /root/
    timedatectl set-timezone Europe/Moscow                                # Укажите ваш часовой пояс
    mdadm --create --verbose --force /dev/md127 --level=10 --raid-devices=4 /dev/sd{c,d,e,f}
    cat /proc/mdstat
    mdadm --detail --scan | awk '/ARRAY/ {print}' >> /etc/mdadm/mdadm.conf
    parted -s /dev/md127 mklabel gpt
    parted /dev/md127 mkpart primary ext4 0% 20% && parted /dev/md127 mkpart primary ext4 20% 40% && \
      parted /dev/md127 mkpart primary ext4 40% 60% && parted /dev/md127 mkpart primary ext4 60% 80% && \
      parted /dev/md127 mkpart primary ext4 80% 100%
    for i in $(seq 1 5); do mkfs.ext4 /dev/md127p"$i"; done
    mkdir -p /raid/part{1,2,3,4,5}
    for i in $(seq 1 5); do echo $(blkid /dev/md127p"$i" | \
       awk '{print $2}') /raid/part"$i" ext4 defaults 1 2 >> /etc/fstab; done
    mount -a
  SHELL
end
