MACHINES = {
  :inetRouter => {
        :box_name => "cdaf/UbuntuLVM",
        :vm_name => "inetRouter",
        :net => [
                    ["192.168.255.1", 2, "255.255.255.248",  "router-net"],
                ]
  },

  :inetRouter2 => {
    :box_name => "cdaf/UbuntuLVM",
    :vm_name => "inetRouter2",
    :net => [
                ["192.168.255.2", 2, "255.255.255.248",  "router-net"],
            ]
},

  :centralRouter => {
        :box_name => "cdaf/UbuntuLVM",
        :vm_name => "centralRouter",
        :net => [
                   ["192.168.255.3",  2, "255.255.255.248",  "router-net"],
                   ["192.168.0.1",    3, "255.255.255.252",  "local-net"],
                ]
  },

  :centralServer => {
        :box_name => "cdaf/UbuntuLVM",
        :vm_name => "centralServer",
        :net => [
                   ["192.168.0.2",    2, "255.255.255.252",  "local-net"],
                ]
  },
}

Vagrant.configure("2") do |config|
  MACHINES.each do |boxname, boxconfig|
    config.vm.define boxname do |box|
      box.vm.box = boxconfig[:box_name]
      box.vm.host_name = boxconfig[:vm_name]

      box.vm.provider "virtualbox" do |v|
        v.memory = 768
        v.cpus = 1
       end

      boxconfig[:net].each do |ipconf|
        box.vm.network("private_network", ip: ipconf[0], adapter: ipconf[1], netmask: ipconf[2], virtualbox__intnet: ipconf[3])
      end

      if boxconfig.key?(:public)
        box.vm.network "public_network", boxconfig[:public]
      end

      box.vm.provision "shell", inline: <<-SHELL
        mkdir -p ~root/.ssh
        cp ~vagrant/.ssh/auth* ~root/.ssh
      SHELL
    end
  end
end
