Vagrant.configure(2) do |config|
  config.vm.box = "centos/7"

  config.vm.provision "shell", inline: <<-SHELL
    cp -r /vagrant/authorized_keys /root/.ssh/authorized_keys             # Добавьте вашу публичную часть ключа
    cp -r /vagrant/.bashrc /home/vagrant && cp -r /vagrant/.bashrc /root/
  SHELL

  config.vm.provider "virtualbox" do |v|
	  v.memory = 256
  end

  config.vm.define "ns01" do |ns01|
    ns01.vm.network "private_network", ip: "192.168.50.10", netmask: "255.255.255.0"
    ns01.vm.hostname = "ns01"
  end

  config.vm.define "ns02" do |ns02|
    ns02.vm.network "private_network", ip: "192.168.50.11", netmask: "255.255.255.0"
    ns02.vm.hostname = "ns02"
  end

  config.vm.define "client" do |client|
    client.vm.network "private_network", ip: "192.168.50.15", netmask: "255.255.255.0"
    client.vm.hostname = "client"
  end

  config.vm.define "client2" do |client2|
    client2.vm.network "private_network", ip: "192.168.50.16", netmask: "255.255.255.0"
    client2.vm.hostname = "client2"
  end

end
