# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.provider "virtualbox" do |vm|
    vm.memory = 4096
    vm.cpus = 2
    vm.check_guest_additions=false
  config.vm.box = "cdaf/UbuntuLVM"
  config.vm.box_version = "2022.10.05"
  config.vm.box_check_update = false
end

  config.vm.define "otus-node-0" do |server|
      server.vm.network "public_network", ip: "172.22.23.105", netmask: "255.255.252.0"
      server.vm.hostname = "otus-node-0.local"
      server.vm.disk :disk, size: "50GB", primary: true
      server.vm.provision "shell", path: "server.sh"
end

  config.vm.define "otus-node-1" do |client|
      client.vm.network "public_network", ip: "172.22.23.106", netmask: "255.255.252.0"
      client.vm.hostname = "otus-node-1.local"
      client.vm.disk :disk, size: "50GB", primary: true
      client.vm.provision "shell", path: "client.sh"
end
end
